---
Title: jQuery 3.xでajax()でエラーになったときに疑う箇所
Category:
- javascript
Date: 2017-01-12T05:00:39+09:00
URL: https://blog.turai.work/entry/20170112/1484164839
EditURL: https://blog.hatena.ne.jp/thr3a/thr3a.hatenablog.com/atom/entry/10328749687205879260
---

なるほど、jQuery 3.0では多くの非推奨メソッドが削除されて2.xで動いていたものが動かなくなることがある

詳しくは以下のサイトが詳しい

[【翻訳まとめ】jQuery 3.0 alpha リリースノート - Qiita](http://qiita.com/fmy/items/abdeeb9abaf56058c20e)

中でもajax()で若干ハマったのでメモ

# success() error() complete() は廃止された

彼らはもういない

ソースは

[http://api.jquery.com/jQuery.ajax/:embed:cite]

に以下のように明記されている

> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.


別にいきなり始まった話ではなく、すでに1.8以降では

> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks will be deprecated in jQuery 1.8. To prepare your code for their eventual removal, use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

と非推奨メソッドになってたんだし妥当


# どうなるの

こんな感じ

```javascript
$.ajax({
  type: "GET",
  url: 'http://localhost:3000/text.php',
  data: {name: 'taro},
  timeout: 3000
}).done(function(data){
  console.log(data);
}).fail(function(data){
  console.log('error',data);
}).always(function(data){
  console.log('always called');
});
```

$.getjson()？知らない子ですね
